/* tslint:disable */
/* eslint-disable */
/**
 * resume-data
 * API for managing my resume data
 *
 * The version of the OpenAPI document: 2023-01-16T13:44:13Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Social
 */
export interface Social {
    /**
     * The name of the social site
     * @type {string}
     * @memberof Social
     */
    name: string;
    /**
     * The url of the social site
     * @type {string}
     * @memberof Social
     */
    url: string;
}

/**
 * Check if a given object implements the Social interface.
 */
export function instanceOfSocial(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function SocialFromJSON(json: any): Social {
    return SocialFromJSONTyped(json, false);
}

export function SocialFromJSONTyped(json: any, ignoreDiscriminator: boolean): Social {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
    };
}

export function SocialToJSON(value?: Social | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'url': value.url,
    };
}

