import CustomAppBar from "@/components/CustomAppBar";
import type { Metadata } from "next";
import "./globals.css";
import ResumeDataProvider from "@/lib/ResumeDataClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ResumeDataProvider>
          <CustomAppBar></CustomAppBar>
          <main className="flex min-h-screen flex-col justify-between p-24">
            {children}
          </main>
        </ResumeDataProvider>
      </body>
    </html>
  );
}
